# Generated by Django 2.0.7 on 2019-06-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionFrame',
            fields=[
                ('ai_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('action', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataFrame',
            fields=[
                ('ai_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('temp', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('co2', models.IntegerField()),
                ('co', models.IntegerField()),
                ('time', models.TimeField()),
                ('charge', models.IntegerField()),
            ],
            options={
                'ordering': ['id', 'temp', 'humidity', 'pressure', 'co2', 'co', 'charge', 'ai_id'],
            },
        ),
    ]
